// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityGuardManagement.Infrastructure.Persistence;

#nullable disable

namespace SecurityGuardManagement.Infrastructure.Migrations
{
    [DbContext(typeof(SecurityGuardDbContext))]
    [Migration("20250218070717_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuardId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("Shift")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuardId");

                    b.HasIndex("PostId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Example Corporation",
                            Status = 1
                        });
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuardId")
                        .HasColumnType("int");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuardId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.EmploymentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuardId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForLeaving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuardId");

                    b.ToTable("EmploymentHistories");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Guard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BankAccountDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DependentContactDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DependentIDNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DependentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DependentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DependentRelations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeployedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentSubmittedNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DocumentsSubmittedStatus")
                        .HasColumnType("bit");

                    b.Property<string>("GuardIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuardLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PoliceReportStatus")
                        .HasColumnType("bit");

                    b.Property<string>("PoliceReportStatusNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuardLevelId");

                    b.ToTable("Guards");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.GuardAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuardId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuardId");

                    b.ToTable("GuardAddresses");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.GuardLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorizationLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GuardLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorizationLevel = 1,
                            BaseSalary = 25000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Entry level security guard",
                            Title = "Junior Guard"
                        },
                        new
                        {
                            Id = 2,
                            AuthorizationLevel = 2,
                            BaseSalary = 35000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Experienced security guard",
                            Title = "Senior Guard"
                        },
                        new
                        {
                            Id = 3,
                            AuthorizationLevel = 3,
                            BaseSalary = 45000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Security supervisor",
                            Title = "Supervisor"
                        });
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequiredGuardCount")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Main entrance security post",
                            Name = "Main Office Security",
                            RequiredGuardCount = 2,
                            Status = 1
                        });
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuardId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("SecurityGuardManagement.Domain.Entities.Guard", "Guard")
                        .WithMany("Assignments")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityGuardManagement.Domain.Entities.Post", "Post")
                        .WithMany("Assignments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guard");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Client", b =>
                {
                    b.OwnsOne("SecurityGuardManagement.Domain.ValueObjects.ContactInformation", "ContactInfo", b1 =>
                        {
                            b1.Property<int>("ClientId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");

                            b1.HasData(
                                new
                                {
                                    ClientId = 1,
                                    Email = "contact@example.com",
                                    Phone = "+9779841000000"
                                });
                        });

                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Education", b =>
                {
                    b.HasOne("SecurityGuardManagement.Domain.Entities.Guard", "Guard")
                        .WithMany("Educations")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guard");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.EmploymentHistory", b =>
                {
                    b.HasOne("SecurityGuardManagement.Domain.Entities.Guard", "Guard")
                        .WithMany("EmploymentHistory")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guard");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Guard", b =>
                {
                    b.HasOne("SecurityGuardManagement.Domain.Entities.GuardLevel", "GuardLevel")
                        .WithMany("Guards")
                        .HasForeignKey("GuardLevelId");

                    b.OwnsOne("SecurityGuardManagement.Domain.ValueObjects.ContactInformation", "ContactInfo", b1 =>
                        {
                            b1.Property<int>("GuardId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("GuardId");

                            b1.ToTable("Guards");

                            b1.WithOwner()
                                .HasForeignKey("GuardId");
                        });

                    b.OwnsOne("SecurityGuardManagement.Domain.ValueObjects.PersonalInformation", "PersonalInfo", b1 =>
                        {
                            b1.Property<int>("GuardId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("DateOfBirth")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FatherName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Gender")
                                .HasColumnType("int");

                            b1.Property<string>("GrandFatherName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("GuardId");

                            b1.ToTable("Guards");

                            b1.WithOwner()
                                .HasForeignKey("GuardId");
                        });

                    b.Navigation("ContactInfo");

                    b.Navigation("GuardLevel");

                    b.Navigation("PersonalInfo");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.GuardAddress", b =>
                {
                    b.HasOne("SecurityGuardManagement.Domain.Entities.Guard", "Guard")
                        .WithMany("GuardAddresses")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guard");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Post", b =>
                {
                    b.HasOne("SecurityGuardManagement.Domain.Entities.Client", "Client")
                        .WithMany("Posts")
                        .HasForeignKey("ClientId");

                    b.OwnsOne("SecurityGuardManagement.Domain.ValueObjects.Address", "PostAddress", b1 =>
                        {
                            b1.Property<int>("PostId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GoogleLocation")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.HasData(
                                new
                                {
                                    PostId = 1,
                                    City = "Kathmandu",
                                    Country = "Nepal",
                                    District = "Kathmandu",
                                    PostalCode = "44600",
                                    Province = "Bagmati",
                                    State = "Bagmati",
                                    Street = "123 Main Street"
                                });
                        });

                    b.Navigation("Client");

                    b.Navigation("PostAddress");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Training", b =>
                {
                    b.HasOne("SecurityGuardManagement.Domain.Entities.Guard", "Guard")
                        .WithMany("Trainings")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guard");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Client", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Guard", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Educations");

                    b.Navigation("EmploymentHistory");

                    b.Navigation("GuardAddresses");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.GuardLevel", b =>
                {
                    b.Navigation("Guards");
                });

            modelBuilder.Entity("SecurityGuardManagement.Domain.Entities.Post", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
